### ISSUE TITLE
It can't support spree 3.0

### ISSUE THREAD

**Issue by caiqinghua** [RuanShan/spree_alipay#14]
Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_auth_devise (>= 0) ruby depends on
      spree_core (~> 3.0.0) ruby

    spree_auth_devise (>= 0) ruby depends on
      spree_core (~> 3.0.0) ruby

    spree (= 3.0.0) ruby depends on
      spree_core (= 3.0.0) ruby

    spree_alipay (>= 0) ruby depends on
      spree_core (~> 2.2.0) ruby

**Comment by qinghe** [comment]
Thanks for report first.
Yes, it do not support spree 3.0 now. i am busy these days, i think i could not  upgrade it recently. Maybe late of June, i could handle it. PR is welcome.

**Comment by qinghe** [comment]
@caiqinghua  it support 3.0 now.
